// <auto-generated by="the Blazor I18n Text compiler" />
namespace Hsf.ApplicationProcess.August2020.Blazor.I18nText
{
    public partial class local : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"This web address does not exist, sorry."</summary>
        public string app_err_address_not_found;

        /// <summary>"HSF e-commerce Applicant demo app"</summary>
        public string app_main_header;

        /// <summary>"Next"</summary>
        public string button_l_next;

        /// <summary>"Previous"</summary>
        public string button_l_previous;

        /// <summary>"Reset"</summary>
        public string button_l_reset;

        /// <summary>"Submit"</summary>
        public string button_l_submit;

        /// <summary>"Address"</summary>
        public string field_address;

        /// <summary>"Age"</summary>
        public string field_age;

        /// <summary>"Country of origin"</summary>
        public string field_country;

        /// <summary>"Email address"</summary>
        public string field_email;

        /// <summary>"Such country does not exist."</summary>
        public string field_err_country;

        /// <summary>"Email format is invalid."</summary>
        public string field_err_email;

        /// <summary>"Name"</summary>
        public string field_name;

        /// <summary>"Applicant is Hired"</summary>
        public string field_status_hired;

        /// <summary>"Family name"</summary>
        public string field_surname;

        /// <summary>"Add new applicant to the database"</summary>
        public string header_new_applicant;

        /// <summary>"Review applicants"</summary>
        public string header_view_applicants;

        /// <summary>"Add Applicant"</summary>
        public string menu_add_applicant;

        /// <summary>"View applicant data"</summary>
        public string menu_get_by_id;

        /// <summary>"Success!"</summary>
        public string toast_h_applicant_added;

        /// <summary>"API rejected sent data!"</summary>
        public string toast_h_bad_param_sent;

        /// <summary>"Connection error!"</summary>
        public string toast_h_connection_err;

        /// <summary>"Applicant has been added: "</summary>
        public string toast_m_applicant_added;

        /// <summary>"Incorrect parameters were sent: "</summary>
        public string toast_m_bad_param_sent;

        /// <summary>"Could not add applicant to database - API is not reachable. Click to try again."</summary>
        public string toast_m_connection_err;
    }
}
