// <auto-generated by="the Blazor I18n Text compiler" />
namespace Hsf.ApplicationProcess.August2020.Blazor.I18nText
{
    public partial class local : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Reset"</summary>
        public string button_l_reset;

        /// <summary>"Submit"</summary>
        public string button_l_submit;

        /// <summary>"Address"</summary>
        public string field_address;

        /// <summary>"Age"</summary>
        public string field_age;

        /// <summary>"Country of origin"</summary>
        public string field_country;

        /// <summary>"Email address"</summary>
        public string field_email;

        /// <summary>"Name"</summary>
        public string field_name;

        /// <summary>"Hired"</summary>
        public string field_status_hired;

        /// <summary>"Family name"</summary>
        public string field_surname;

        /// <summary>"Add new applicant to the database"</summary>
        public string header_new_applicant;
    }
}
